services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minirutter

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata: